- id: '1625693270586'
  alias: Espresso machine empty?
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.shelly_espresso
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 10
  condition:
  - condition: numeric_state
    entity_id: sensor.shelly_espresso_power
    below: 100
  action:
  - service: notify.notify
    data:
      title: Espresso machine has no water!
      message: Espresso machine has no water!
  mode: single
- id: '1682950358831'
  alias: LG webOS Smart TV - Turn On Action
  description: ''
  use_blueprint:
    path: cvroque/webostv_turn_on.yaml
    input:
      webostv: media_player.lg_tv
      webostv_mac: ec-6c-9a-b1-04-aa
- id: '1683447191864'
  alias: Espresso machine on
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: espresso machine on
  condition: []
  action:
  - type: turn_on
    device_id: 8af4e7817d94eff591c631230ce2d848
    entity_id: switch.shelly_espresso
    domain: switch
  mode: single
- id: '1683447638096'
  alias: Espresso machine off
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: espresso machine off
  condition: []
  action:
  - type: turn_off
    device_id: 8af4e7817d94eff591c631230ce2d848
    entity_id: switch.shelly_espresso
    domain: switch
  mode: single
- id: '1690212207917'
  alias: Kamer Roba licht aan wanneer power++
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 2ff204460aa007180471a6f77c0749c8
    entity_id: 2951ac36d049de8229ec20edc5a94e78
    domain: sensor
    above: 10
  - type: power
    platform: device
    device_id: 870dfc6902f4a10a5ad4fce64d432af4
    entity_id: 6d268a5b3723993d35376b0850f2a986
    domain: sensor
    above: 5
  condition:
  - type: is_power
    condition: device
    device_id: 2ff204460aa007180471a6f77c0749c8
    entity_id: 2951ac36d049de8229ec20edc5a94e78
    domain: sensor
    above: 10
  - type: is_power
    condition: device
    device_id: 870dfc6902f4a10a5ad4fce64d432af4
    entity_id: 6d268a5b3723993d35376b0850f2a986
    domain: sensor
    above: 5
  action:
  - type: turn_on
    device_id: 7c7145ccb6e10ad91744a0b80af2136e
    entity_id: 6782b2ac42f4ab812c7ecd02804dd596
    domain: light
  mode: single
- id: '1690212321369'
  alias: Kamer Roba licht uit wanneer power--
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 2ff204460aa007180471a6f77c0749c8
    entity_id: 2951ac36d049de8229ec20edc5a94e78
    domain: sensor
    below: 10
  - type: power
    platform: device
    device_id: 870dfc6902f4a10a5ad4fce64d432af4
    entity_id: 6d268a5b3723993d35376b0850f2a986
    domain: sensor
    below: 5
  condition:
  - type: is_power
    condition: device
    device_id: 870dfc6902f4a10a5ad4fce64d432af4
    entity_id: 6d268a5b3723993d35376b0850f2a986
    domain: sensor
    below: 5
  - type: is_power
    condition: device
    device_id: 2ff204460aa007180471a6f77c0749c8
    entity_id: 2951ac36d049de8229ec20edc5a94e78
    domain: sensor
    below: 10
  action:
  - type: turn_off
    device_id: 7c7145ccb6e10ad91744a0b80af2136e
    entity_id: 6782b2ac42f4ab812c7ecd02804dd596
    domain: light
  mode: single
