- id: '1578097773726'
  alias: tradfri round button on/off
  description: ''
  trigger:
  - event_data:
      event: 1002
      id: tradfri_remote_control
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - type: toggle
    device_id: 86f702776f6f66573bb05544b55075ad
    entity_id: humidifier.humidifier
    domain: humidifier
  - type: toggle
    device_id: d86d7c82ec0be311ca273f963775c640
    entity_id: switch.shellyplug_s_e868e7c5781f
    domain: switch
  mode: single
- id: '1578143746974'
  alias: Start HomeKit
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 0:05
  - service: homekit.start
- id: '1593296347730'
  alias: Switch off humidifier when TV light switches off after dark
  description: ''
  trigger:
  - entity_id: light.klein_lampje_bij_tv
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data: {}
    entity_id: fan.xiaomi_miio_device
    service: fan.turn_off
- id: '1593297250598'
  alias: Switch on humidifier when espresso machine switches on
  description: ''
  trigger:
  - entity_id: switch.espresso_machine_switch
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: fan.xiaomi_miio_device
    service: fan.turn_on
  mode: single
- id: '1593297316676'
  alias: Switch off humidifier when we leave the house
  description: ''
  trigger:
  - below: '50'
    entity_id: sensor.home_occupancy_confidence
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: fan.xiaomi_miio_device
    service: fan.turn_off
- id: '1593297511540'
  alias: Switch on humidifier when we arrive home
  description: ''
  trigger:
  - above: '80'
    entity_id: sensor.home_occupancy_confidence
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: fan.xiaomi_miio_device
    service: fan.turn_on
- id: '1597531227645'
  alias: kill standby stuff at night
  description: ''
  trigger:
  - at: 03:00
    platform: time
  condition:
  - condition: device
    device_id: fa11229bab194729875f095e353152d4
    domain: light
    entity_id: light.klein_lampje_bij_tv
    type: is_off
  action:
  - data: {}
    entity_id: switch.stekkerblok_5_instance_4_subwoofer_switch
    service: switch.turn_off
  - service: switch.turn_off
    data: {}
    entity_id: switch.stekkerblok_2_instance_1_amplifier_switch
  - service: switch.turn_off
    data: {}
    entity_id: switch.stekkerblok_5_instance_6_ps4_switch
  mode: single
- id: '1622585810139'
  alias: Switch off ventilation
  description: ''
  trigger:
  - platform: time
    at: input_datetime.ventilation_switch_off_time
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.fgwpe_f_wall_plug_ventilation_switch
  mode: single
- id: '1622585844091'
  alias: Switch on ventilation
  description: ''
  trigger:
  - platform: time
    at: input_datetime.ventilation_switch_on_time
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.fgwpe_f_wall_plug_ventilation_switch
  mode: single
- id: '1625693270586'
  alias: Espresso machine empty?
  description: ''
  trigger:
  - platform: state
    entity_id: switch.espresso_machine_switch
    to: 'on'
    for: 00:00:10
  condition:
  - condition: numeric_state
    entity_id: sensor.espresso_machine_power
    below: '10'
  action:
  - service: notify.notify
    data:
      title: Espresso machine has no water!
      message: Espresso machine has no water!
  mode: single
- id: '1660249755304'
  alias: switch off fan at night
  description: ''
  trigger:
  - platform: time
    at: input_datetime.shut_off_fan_at_night
  condition: []
  action:
  - type: turn_off
    device_id: d86d7c82ec0be311ca273f963775c640
    entity_id: switch.shellyplug_s_e868e7c5781f
    domain: switch
  mode: single
- id: '1664478197364'
  alias: action espresso machine on
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: espresso machine on
  condition: []
  action:
  - type: turn_on
    device_id: 58a3f77bb18d6e385ee8936633df1aa0
    entity_id: switch.espresso_machine_switch
    domain: switch
  mode: single
- id: '1664478233109'
  alias: action espresso machine off
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: espresso machine off
  condition: []
  action:
  - type: turn_off
    device_id: 58a3f77bb18d6e385ee8936633df1aa0
    entity_id: switch.espresso_machine_switch
    domain: switch
  mode: single
- id: '1664478553109'
  alias: action a/v on
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: a/v on
  condition: []
  action:
  - service: homeassistant.turn_on
    data: {}
    target:
      entity_id: group.avstuff
  mode: single
- id: '1664478596991'
  alias: action a/v off
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: a/v off
  condition: []
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id: group.avstuff
  mode: single
- id: '1664478647915'
  alias: action toggle bed lights
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: toggle bed lights
  condition: []
  action:
  - service: homeassistant.toggle
    data: {}
    target:
      entity_id: group.bedlights
  mode: single
