default_config:

homeassistant:
  customize: !include customize.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info

# Text to speech; uses google translate to convert to mp3
tts:
  - platform: google_translate
    language: 'nl'

# Push history to mariadb instead of the default sqlite. Keep history for 15 days.
# Older history is gradually pushed into influxdb.
recorder:
  purge_keep_days: 15
  db_url: !secret recorder_db_url

# configure influxdb connection. 
influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state

# various includes for groups, automation and scenes.
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# notify configuration using google firebase; this enables desktop browser notifications.
notify:
    - platform: html5
      name: home_assistant_notifier
      vapid_pub_key: !secret notify_vapid_pub_key
      vapid_prv_key: !secret notify_vapid_prv_key
      vapid_email: !secret notify_vapid_email

# 'breaking changes' addon from HACS
breaking_changes:

# set up the toon integration. 
toon:
  client_id: !secret toon_client_id
  client_secret: !secret toon_client_secret

# WiP: homekit config. very incomplete.
homekit:
  advertise_ip: !secret hassio_host_ip
  filter: 
        include_entities:
          - light.grote_lamp_bij_raam
          - light.klein_lampje_bij_tv
          - light.klein_lampje_tafel
          - light.zuiver
          - switch.stekkerblok_10_instance_2_light_right_switch_3
          - switch.stekkerblok_10_instance_5_light_left_switch_3
          - switch.espresso_machine_switch
          - climate.thermostat
          - switch.stekkerblok_2_instance_1_amplifier_switch
          - switch.stekkerblok_5_instance_4_subwoofer_switch

# sync car status and location from the connecteddrive portal.
bmw_connected_drive:
  name:
    username: !secret bmw_username
    password: !secret bmw_password
    region: "rest_of_world"

# sensors are defined in the sensors directory; one yaml per 'theme'.
sensor: !include_dir_merge_list sensors/

# Bosch/Siemens 'home connect' integration; enables dishwasher and fridge sensors and stats.
home_connect:
   client_id: !secret home_connect_client_id
   client_secret: !secret home_connect_client_secret

#media_player:
#  - platform: onkyo
#    host: !secret onkyo_ip
#    name: onkyo

# Xiaomi humidifier setup
#fan:
#  - platform: xiaomi_miio
#    host: !secret xiaomi_humidifier_ip
#    token: !secret xiaomi_humidifier_token

# sonos connection
sonos:
  media_player:
    hosts:
      - !secret sonos_ip

#badnest:
#   issue_token: !secret badnest_issue_token
#    cookie: !secret badnest_cookie
#    region: eu

binary_sensor:
 - platform: workday
   country: NL

emulated_hue:
  listen_port: 4280
  advertise_ip: !secret hue_ip_address
  host_ip: !secret hassio_host_ip
  advertise_port: 80

wake_on_lan:

withings:
  client_id: 74aad65a7204bab1efcf0b1bf8d515fcd7890f04b9a2723f2fbfe732ffc8a2cd
  client_secret: a58cfe93899e7283d49e05ba1c40414f30d70d79032f36b178de0e61387449d8
  use_webhook: true

light:
  - platform: template
    lights:
      rvdm_sleep_lights:
        friendly_name: "rvdm sensor sleep"
        turn_on:
        - service: input_select.select_option
          data_template:
            entity_id: input_select.rvdm_status_dropdown
            option: 'Just Awake'
        turn_off:
        - service: input_select.select_option
          data_template:
            entity_id: input_select.rvdm_status_dropdown
            option: 'Sleeping'

utility_meter:
        daily_power:
                source: sensor.energy_usage_today
                cycle: daily
        daily_gas:
                source: sensor.gas_usage_today
                cycle: daily

