default_config:

lovelace:
  mode: storage

homeassistant:
  customize: !include customize.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  cors_allowed_origins:
    - https://unpkg.com
    - https://unpkg.com/lit-html@1/directives/style-map.js?module
    - https://unpkg.com/lit-html@1/directives/if-defined?module
    - https://unpkg.com/lit-html@%5E1.0.0?module
    - https://unpkg.com/lit-html@1/directives/style-map.js?module

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info

# Text to speech; uses google translate to convert to mp3
tts:
  - platform: google_translate
    language: 'nl'

# Push history to mariadb instead of the default sqlite. Keep history for 15 days.
# Older history is gradually pushed into influxdb.
recorder:
  purge_keep_days: 15
  db_url: !secret recorder_db_url

# configure influxdb connection. 
influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state

# various includes for groups, automation and scenes.
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# notify configuration using google firebase; this enables desktop browser notifications.
notify:
    - platform: html5
      name: home_assistant_notifier
      vapid_pub_key: !secret notify_vapid_pub_key
      vapid_prv_key: !secret notify_vapid_prv_key
      vapid_email: !secret notify_vapid_email

# WiP: homekit config. very incomplete.
homekit:
- advertise_ip: !secret hassio_host_ip
- port: 21163
  name: Holterweg_roba
  filter: 
    include_entities:
       - light.gang_lampen
       - light.kamer_nekomo_lampen
       - light.kamer_roba_lampen
       - light.kantoor_lampen
       - light.keuken_lampen
       - light.overloop_lampen
       - light.slaapkamer_lampen
       - light.woonkamer_lampen
       - switch.shelly_espresso
       - switch.shelly_magnetron
- port: 21164
  name: Holterweg_nekomo
  filter:
     include_entities:
       - light.gang_lampen
       - light.kamer_nekomo_lampen
       - light.kamer_roba_lampen
       - light.kantoor_lampen
       - light.keuken_lampen
       - light.overloop_lampen
       - light.slaapkamer_lampen
       - light.woonkamer_lampen
       - switch.shelly_espresso
       - switch.shelly_magnetron

# sensors are defined in the sensors directory; one yaml per 'theme'.
sensor: !include_dir_merge_list sensors/

# Bosch/Siemens 'home connect' integration; enables dishwasher and fridge sensors and stats.
# deprecated
#home_connect:
#   client_id: !secret home_connect_client_id
#   client_secret: !secret home_connect_client_secret

zha:
  zigpy_config:
    ota:
      otau_directory: /config/zigpy_ota
      ikea_provider: true
    network:
      channel: 15             # What channel the radio should try to use.
      channels: [15, 20, 25]  # Channel mask

zha_toolkit:

#media_player:
#  - platform: onkyo
#    host: !secret onkyo_ip
#    name: onkyo

# Xiaomi humidifier setup
#fan:
#  - platform: xiaomi_miio
#    host: !secret xiaomi_humidifier_ip
#    token: !secret xiaomi_humidifier_token

# sonos connection
sonos:
  media_player:
    hosts:
      - !secret sonos_ip

#badnest:
#   issue_token: !secret badnest_issue_token
#    cookie: !secret badnest_cookie
#    region: eu

emulated_hue:
  listen_port: 4280
  advertise_ip: !secret hue_ip_address
  host_ip: !secret hassio_host_ip
  advertise_port: 80

wake_on_lan:

# deprecated 20-10
#withings:
#  client_id: !secret withings_client_id
#  client_secret: !secret withings_client_secret
#  use_webhook: true

light:
  - platform: template
    lights:
      rvdm_sleep_lights:
        friendly_name: "rvdm sensor sleep"
        turn_on:
        - service: input_select.select_option
          data_template:
            entity_id: input_select.rvdm_status_dropdown
            option: 'Just Awake'
        turn_off:
        - service: input_select.select_option
          data_template:
            entity_id: input_select.rvdm_status_dropdown
            option: 'Sleeping'

utility_meter:
        daily_power:
                source: sensor.energy_usage_today
                cycle: daily
        daily_gas:
                source: sensor.gas_usage_today
                cycle: daily

mqtt:
  sensor:
          - name: 'Day-ahead-price'
            unit_of_measurement: "€"
            state_topic: enstoe/day-ahead
            value_template: '{{ value_json.day_ahead_price }}'
            json_attributes_topic: enstoe/day-ahead

template:
  - trigger:
      platform: time
      at: "23:59:01"
    sensor:
    - name: degree_day_daily
      state: >
        {% set regularized_temp = 18.0 | float %}
        {% set average_outside_temp = states('sensor.outside_temperature_avg') | float %}
        {% set dd = regularized_temp - average_outside_temp %}
        {% if dd > 0 %}
          {{ dd }}
        {% else %}
          0
        {% endif %}      
      unit_of_measurement: 'DD'
  - trigger:
      platform: time
      at: "23:59:59"
    sensor:
    - name: gas_m3_per_degree_day
      state: >
        {% set gas_usage = states('sensor.gas_delivery_daily') | float %}
        {% set dd = states('sensor.degree_day_daily') | float %}
        {% if dd > 0 %}
          {{ gas_usage / dd }}
        {% else %}
          0
        {% endif %}      
      unit_of_measurement: 'm³/DD'

rest: !include rest.yaml

ffmpeg:

afvalbeheer:
        wastecollector: circulus
        resources:
                - restafval
                - gft
                - papier
                - pmd
        postcode: 7434PA
        streetnumber: 115
        upcomingsensor: 1
        builtinicons: 1
        builtiniconsnew: 1
        dutch: 1
        dayofweek: 1
        alwaysshowday: 1

evohome:
  username: !secret evohome_username
  password: !secret evohome_password
  scan_interval: 180

rest_command:
  reboot_p1_dongle:
    url: 192.168.43.68/ReBoot
    method: get

powercalc:

ramses_cc:
  serial_port: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0
  packet_log:
    file_name: packet.log
    rotate_backups: 28
  restore_cache: true
  scan_interval: 60
  01:010995:
    system: 
      appliance_control: 10:058452
    zones:
      "00": { _name: "Keuken", sensor: 34:074351, actuators: [ 04:122018 ] }
      "01": { _name: "Roba kamer", sensor: 04:122022, actuators: [ 04:122022 ] }
      "02": { _name: "Nekomo kamer", sensor: 04:122020, actuators: [ 04:122020 ] }
  known_list:
    01:010995: # system
    10:058452: # opentherm gw
    34:074351: # sensor keuken
    04:122018: # actuator keuken
    04:122022: # sensor roba kamer
    04:122022: # actuator roba kamer
    04:122020: # sensor nekomo kamer
    04:122020: # actuator nekomo kamer
    18:262143: # evofw3
  ramses_rf:
    enforce_known_list: true
