default_config:
        
homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
    language: 'nl'

recorder:
  purge_keep_days: 15
  db_url: !secret recorder_db_url

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

notify:
    - platform: html5
      name: home_assistant_notifier
      vapid_pub_key: !secret notify_vapid_pub_key
      vapid_prv_key: !secret notify_vapid_prv_key
      vapid_email: !secret notify_vapid_email

breaking_changes:

toon:
  client_id: !secret toon_client_id
  client_secret: !secret toon_client_secret

homekit:
  auto_start: false
  advertise_ip: !secret hassio_host_ip
  filter:
    include_entities:
      - switch.raam_lamp_52
      - switch.espresso_machine_53
      - scene.a_v_off
      - scene.a_v_on
      - climate.toon_thermostat

bmw_connected_drive:
  name:
    username: !secret bmw_username
    password: !secret bmw_password
    region: "rest_of_world"

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state

sensor: !include_dir_merge_list sensors/

home_connect:
   client_id: !secret home_connect_client_id
   client_secret: !secret home_connect_client_secret

#media_player:
#  - platform: onkyo
#    host: !secret onkyo_ip
#    name: onkyo

fan:
  - platform: xiaomi_miio
    host: !secret xiaomi_humidifier_ip
    token: !secret xiaomi_humidifier_token

sonos:
  media_player:
    hosts:
      - !secret sonos_ip
