- platform: template
  sensors:
    dishwasher_progress_non0:
      friendly_name: Dishwasher program progress
      unit_of_measurement: "%"
      value_template: >-
        {% if states("sensor.nekodishwasher_program_progress") in ['unknown', 'unavailable', 'none']  %}
          0
        {% else %}
          {{ states("sensor.nekodishwasher_program_progress") }}
        {% endif %}
