- platform: template
  sensors:
     purifier_fan_mode:
       friendly_name: "Mode"
       value_template: "{{ states.fan.xiaomi_miio_device.attributes.mode }}"
     purifier_fan_speed:
       friendly_name: "Motor speed"
       unit_of_measurement: 'rpm'
       value_template: "{{ states.fan.xiaomi_miio_device.attributes.motor_speed }}"
     purifier_temperature:
       friendly_name: "Temperature"
       unit_of_measurement: 'C°'
       value_template: "{{ states.fan.xiaomi_miio_device.attributes.temperature }}"
     purifier_humidity:
       friendly_name: "Humidity"
       unit_of_measurement: '%'
       value_template: "{{ states.fan.xiaomi_miio_device.attributes.humidity }}"
     purifier_child_lock:
       friendly_name: "Child Lock"
       value_template: "{{ states.fan.xiaomi_miio_device.attributes.child_lock }}"
     purifier_buzzer:
       friendly_name: "Buzzer"
       value_template: "{{ states.fan.xiaomi_miio_device.attributes.buzzer }}"
     purifier_target_humidity:
       friendly_name: "Target Humidity"
       value_template: "{{ states.fan.xiaomi_miio_device.attributes.target_humidity }}"
     purifier_depth:
       friendly_name: "Depth"
       value_template: "{{ states.fan.xiaomi_miio_device.attributes.depth }}"
     purifier_dry:
       friendly_name: "Dry"
       value_template: "{{ states.fan.xiaomi_miio_device.attributes.dry }}"
