- platform: mqtt
  state_topic: 'monitor/presence_monitor/rvdm_iphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'presence_rvdm_iphone'

- platform: mqtt
  state_topic: 'monitor/presence_monitor/tomomi_iphone'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'presence_tomomi_iphone'

- platform: min_max
  name: "Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.presence_rvdm_iphone
    - sensor.presence_tomomi_iphone
